In [0]:
import numpy as np

In [165]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [166]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1

arr1[:,::2] ## extracting the full row and taking col by maintaing gap of 1 from arr1

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [167]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 

arr1[::3,::2] ## extracting the row by maintaing a gap of 2 row from arr1 and taking col by maintaing gap of 1 from arr1

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [210]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 100

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[7880, 9840, 2471, 6336, 3834],
       [5185, 3584, 4020, 1841, 9632]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [211]:
# Q3. Write a code to normalize arr2.

Xma = arr2.max()  ## max value in arr2 
xmi = arr2.min()  ## min value of arr2
newx = (arr2-xmi)/(xma-xmi)  ## new scaled array generated

newx


array([[1.20083516, 1.59057467, 0.12527341, 0.89381587, 0.39630145],
       [0.66494333, 0.34658978, 0.43328694, 0.        , 1.54921456]])

In [212]:

## row wise normalization
X = arr2[0,:]             ## 1st row of arr2 array
xma = max(X)              ## max value of 1st row of the arr2
xmi = min(X)              ## min value of 1st row of the arr2
newx = (X-mi)/(ma-mi)     ## new scaled 1st row of arr2
y = arr2[1,:]             ## 2nd row of arr2 array
yma = max(y)              ## max value of 2nd row of the arr2
ymi = min(y)              ## min value of 2nd row of the arr2
newy = (y-ymi)/(yma-ymi)  ## new scaled 2nd row of arr2
newarr2 = np.array([newx,newy]) ## new scaled arr2 generated
newarr2

array([[1.22642751, 1.54895508, 0.33635017, 0.97235478, 0.56063847],
       [0.42921319, 0.22371968, 0.27968168, 0.        , 1.        ]])

In [175]:
np.percentile(arr1,25)

9.75

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [176]:
# Q4. How would you check if your numpy array has some missing values?

w = np.array([[1,2,45],[4,np.nan,89]]) ## taking a numpy array with null value

np.isnan(w) #this function verifies each element of np array "w" and returns a 'bool' type array which contains true and false depending upon the null value present or not in "W" respectivly
# Hint: Thoda research karo numpy me existing functions hai

array([[False, False, False],
       [False,  True, False]])

In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40


def my_func(arr,n): # function
  if 0<n<=len(arr):                           ## 2nd parameter entered by the user is in the range or not is verified
    print(np.sort(a)[-n]) ## as sort() gives a ascending oder of the array as an output so, negative indexing provides the "index-number"th highest value present in the array 
  else:
    print("Put The Value Of 2nd parameter in the range of 1 to length of array") ## else part of the if






In [214]:

my_func((12, 34, 40, 7, 1, 0),3) ## test case 1: function gives the 3rd highest number

12


In [215]:
my_func((12, 34, 40, 7, 1, 0),1) ## test case 2: function gives the 1st highest number


40


In [216]:
my_func((12, 34, 40, 7, 1, 0),-1) ## test case 3: function dosn't take 2nd parameter as negative

Put The Value Of 2nd parameter in the range of 1 to length of array


In [221]:
my_func((12, 34, 40, 7, 1, 0),7) ## test case 3: function dosn't take 2nd parameter above the range of it's length

Put The Value Of 2nd parameter in the range of 1 to length of array
